module.exports.trains = [
    {
      trainNumber: "12301",
      trainName: "Rajdhani Express",
      source: "Delhi",
      destination: "Mumbai",
      departure: "06:00",
      arrival: "14:00",
      duration: "8h",
      class: ["First", "Second"],
      availableSeats: 45,
      price: {
        First: 2500,
        Second: 1500,
      },
    },
    {
      trainNumber: "12422",
      trainName: "Shatabdi Express",
      source: "Delhi",
      destination: "Lucknow",
      departure: "07:30",
      arrival: "13:00",
      duration: "5.5h",
      class: ["First", "Second"],
      availableSeats: 30,
      price: {
        First: 1800,
        Second: 900,
      },
    },
    {
      trainNumber: "12627",
      trainName: "Karnataka Express",
      source: "Bhopal",
      destination: "Bangalore",
      departure: "18:00",
      arrival: "12:00",
      duration: "18h",
      class: ["First", "Second"],
      availableSeats: 22,
      price: {
        First: 3000,
        Second: 1700,
      },
    },
    {
      trainNumber: "12345",
      trainName: "Lucknow Mail",
      source: "Lucknow",
      destination: "Delhi",
      departure: "22:00",
      arrival: "05:00",
      duration: "7h",
      class: ["First", "Second"],
      availableSeats: 40,
      price: {
        First: 2200,
        Second: 1100,
      },
    },
    {
      trainNumber: "12903",
      trainName: "Golden Temple Mail",
      source: "Amritsar",
      destination: "Mumbai",
      departure: "15:00",
      arrival: "08:00",
      duration: "17h",
      class: ["First", "Second"],
      availableSeats: 18,
      price: {
        First: 2600,
        Second: 1600,
      },
    },
    {
      trainNumber: "12691",
      trainName: "Bangalore Rajdhani",
      source: "Delhi",
      destination: "Bangalore",
      departure: "20:50",
      arrival: "06:40",
      duration: "33h",
      class: ["First", "Second"],
      availableSeats: 50,
      price: {
        First: 3200,
        Second: 1900,
      },
    },
        {
    trainNumber: "12345",
    trainName: "Shatabdi Express",
    source: "Lucknow",
    destination: "Delhi",
    departure: "22:00",
    arrival: "05:00",
    duration: "7h",
    price: {
      First: 1200,
      Second: 800,
      Sleeper: 500,
    },
  },
  {
    trainNumber: "12345",
    trainName: "Shatabdi Express",
    source: "Lucknow",
    destination: "Delhi",
    departure: "22:00",
    arrival: "05:00",
    duration: "7h",
    price: {
      First: 1200,
      Second: 800,
      Sleeper: 500,
    },
  },
  {
    trainNumber: "12346",
    trainName: "Rajdhani Express",
    source: "Lucknow",
    destination: "Delhi",
    departure: "23:30",
    arrival: "06:30",
    duration: "7h",
    price: {
      First: 1500,
      Second: 1000,
      Sleeper: 600,
    },
  },
  {
    trainNumber: "12346",
    trainName: "Rajdhani Express",
    source: "Lucknow",
    destination: "Delhi",
    departure: "23:30",
    arrival: "06:30",
    duration: "7h",
    price: {
      First: 1500,
      Second: 1000,
      Sleeper: 600,
    },
  },
  ];
  